DROP TABLE ORDER_DETAIL;
DROP table ORDERS;
DROP TABLE USERS;
DROP TABLE DISHES;
DROP TABLE RESTAURANTS;

---RESTAURANTS---
CREATE TABLE RESTAURANTS (
ID_RESTAURANT INTEGER CONSTRAINT PK_IDRESTAURANT PRIMARY KEY,
NAME VARCHAR2(30),
NATION VARCHAR2(30),
STARS INTEGER
);

---DISHES---
CREATE TABLE DISHES (
ID_DISH INTEGER CONSTRAINT PK_IDDISH PRIMARY KEY,
DNAME VARCHAR2(30),
ID_RESTAURANT INTEGER,
DTYPE VARCHAR2(30),
PRICE VARCHAR2(5),
CONSTRAINT FK_IDRESTAURANT FOREIGN KEY(ID_RESTAURANT) REFERENCES RESTAURANTS(ID_RESTAURANT)
);

---USERS---
CREATE TABLE USERS (
ID_USER INTEGER CONSTRAINT PK_IDUSER PRIMARY KEY,
UNAME VARCHAR2(30),
USERNAME VARCHAR2(30),
UPASSWORD VARCHAR(30),
UROLE VARCHAR(15)
);


--DETALLES PEDIDOS--
CREATE TABLE ORDER_DETAIL(
ID_ORDER INTEGER CONSTRAINT PK_IDORDER PRIMARY KEY,
ORDER_DATE TIMESTAMP,
DETAILS VARCHAR2(300),
ADRESS VARCHAR2(100),
PAID CHAR(1) DEFAULT 'N',
CONSTRAINT CHK_PAID CHECK(PAID IN ('Y','N'))
);

---ORDERS---
CREATE TABLE ORDERS (
ID_ORDER INTEGER,
ID_USER INTEGER,
ID_RESTAURANT INTEGER,
ID_DISH INTEGER,
CONSTRAINT FK_IDUSER FOREIGN KEY(ID_USER) REFERENCES USERS(ID_USER),
CONSTRAINT FK_IDRESTAURANT_ORD FOREIGN KEY(ID_RESTAURANT) REFERENCES RESTAURANTS(ID_RESTAURANT),
CONSTRAINT FK_IDDISH FOREIGN KEY(ID_DISH) REFERENCES DISHES(ID_DISH),
CONSTRAINT FK_IDORDER FOREIGN KEY(ID_ORDER) REFERENCES ORDER_DETAIL(ID_ORDER)
);



CREATE SEQUENCE SECUENCIA_RESTAURANT
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE;

CREATE OR REPLACE TRIGGER TRIGGER_ID_RESTAURANT
BEFORE INSERT ON RESTAURANTS
FOR EACH ROW
BEGIN
    SELECT SECUENCIA_RESTAURANT.NEXTVAL INTO :NEW.ID_RESTAURANT FROM dual;
END;
/


CREATE SEQUENCE SECUENCIA_DISH
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE;

CREATE OR REPLACE TRIGGER TRIGGER_ID_DISH
BEFORE INSERT ON DISHES
FOR EACH ROW
BEGIN
    SELECT SECUENCIA_DISH.NEXTVAL INTO :NEW.id_DISH FROM dual;
END;
/

CREATE SEQUENCE SECUENCIA_USER
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE;

CREATE OR REPLACE TRIGGER TRIGGER_ID_USER
BEFORE INSERT ON USERS
FOR EACH ROW
BEGIN
    SELECT SECUENCIA_USER.NEXTVAL INTO :NEW.id_USER FROM dual;
END;
/

CREATE SEQUENCE SECUENCIA_ORDER
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE;

CREATE OR REPLACE TRIGGER TRIGGER_ID_ORDER
BEFORE INSERT ON ORDER_DETAIL
FOR EACH ROW
BEGIN
    SELECT SECUENCIA_ORDER.NEXTVAL INTO :NEW.ID_ORDER FROM dual;
END;
/

